name: devlopment
on:
  push:
    branches:
      - main #push 발생하면 아래 작업 진행할 브랜치 이름 적어주면 됨
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # 깃허브 저장소 코드 가져오기
      - name: Install Project
        run: yarn # 빌드 실행
      - name: Build Project
        run: yarn build || { echo "❌ Build failed!"; exit 1; } # 빌드 실행

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: 빌드 성공..!
        run: echo "@@@@@@@@@@@@@@@@빌드 성공@@@@@@@@@@@@@@@@@;
